#!/bin/bash
# Regenerate progress.md as a roll-up of per-session append-only logs.
#
# Why: multiple concurrent Claude/deepseek sessions edit this repo. A shared,
# hand-edited progress.md caused a real stale-read clobber (see progress.md
# history, commit ca56319). Each session now appends ONLY to its own file at
# progress/<slug>.md (never touched by another session — no read-modify-write
# race is possible). This script concatenates those files, ordered oldest to
# newest by mtime, into progress.md.
#
# Safe to run at any time by any session: it only reads progress/*.md and
# overwrites progress.md, never the per-session sources. A concurrent run just
# produces a slightly-stale-but-harmless roll-up, never lost data.
#
# Usage: bash scripts/merge-session-logs.sh

set -euo pipefail
cd "$(dirname "$0")/.."

OUT="progress.md"
DIR="progress"

if [ ! -d "$DIR" ] || [ -z "$(ls -A "$DIR"/*.md 2>/dev/null)" ]; then
  echo "No per-session logs found in $DIR/ — nothing to merge." >&2
  exit 0
fi

{
  echo "# Progress"
  echo
  echo "_Generated by scripts/merge-session-logs.sh — do not hand-edit; edit progress/<your-session-slug>.md instead._"
  echo
  for f in $(ls -t -r "$DIR"/*.md); do
    echo "---"
    echo
    echo "<!-- source: $f -->"
    echo
    cat "$f"
    echo
  done
} > "$OUT"

echo "Wrote $OUT from $(ls "$DIR"/*.md | wc -l) session log(s)."
